"""Selector-only GRPO post-training for WorldEngine DiffusionDrive.

This config inherits the official DiffusionDrive model unchanged.  The new
planning head loads the epoch-100 checkpoint with matching parameter names,
freezes perception and trajectory generation, and trains only the final
``plan_cls_branch`` that selects among the 20 generated trajectories.

The rollout/reward dataset must replace the ordinary 8192-vocabulary ``score``
cache with a ``(B, 20)`` tensor aligned with the candidates generated by the
same forward pass.  Online batched PDM scoring is intentionally a separate
follow-up module.
"""

import os


_base_ = ["./e2e_diffusiondrive.py"]

custom_imports = dict(
    imports=[
        "mmdet3d_plugin",
        "mmdet3d_plugin.navformer.dense_heads.diffusion_grpo_planning_head",
    ]
)

WORLDENGINE_ROOT = os.getenv("WORLDENGINE_ROOT", os.path.abspath("."))
DEFAULT_DIFFUSIONDRIVE_CHECKPOINT = (
    "/inspire/hdd/project/roboticsystem2/wangcaojun-240208020180/"
    "repo-wcj/WorldEngine/experiments/diffusiondrive/e2e_diffusiondrive/epoch_100.pth"
)

# This environment variable makes the experiment portable without changing
# the reviewed config or the senior's repository/checkpoint.
load_from = os.getenv(
    "DIFFUSIONDRIVE_SELECTOR_INIT_CHECKPOINT",
    DEFAULT_DIFFUSIONDRIVE_CHECKPOINT,
)

model = dict(
    process_perception=False,
    freeze_img_backbone=True,
    freeze_img_neck=True,
    freeze_bn=True,
    freeze_bev_encoder=True,
    planning_head=dict(
        type="DiffusionGRPOSelectorPlanningHead",
        selector_layer=-1,
        train_all_selector_layers=False,
        reward_key="score",
        policy_loss_weight=1.0,
        entropy_weight=0.01,
        advantage_epsilon=1e-6,
        minimum_reward_std=1e-6,
        clip_advantage_lower_quantile=0.0,
        clip_advantage_upper_quantile=1.0,
    ),
)

# Only selector parameters have requires_grad=True, so the optimizer cannot
# update the frozen DiffusionDrive generator even though the full checkpoint
# is loaded.
optimizer = dict(
    _delete_=True,
    type="AdamW",
    constructor="DiffusionGRPOSelectorOptimizerConstructor",
    lr=1e-5,
    weight_decay=1e-4,
)
lr_config = dict(_delete_=True, policy="Fixed")

total_epochs = 8
runner = dict(type="EpochBasedRunner", max_epochs=total_epochs)
evaluation = dict(interval=1)
checkpoint_config = dict(interval=1, max_keep_ckpts=2)
find_unused_parameters = True

# Machine-readable contract for the rollout/reward adapter implemented next.
selector_reward_contract = dict(
    key="score",
    num_candidates=20,
    candidate_tensor="candidate_trajectories",
    candidate_shape="(B, 20, 40, 3)",
    reward_shape="(B, 20)",
    reject_navsim_vocabulary_cache=True,
)
