#!/usr/bin/env python3
"""R0: replay trained selectors on immutable epoch-100 closed-loop candidates.

This is a counterfactual ranking diagnostic.  It does not claim an on-policy
closed-loop result because the states and candidate sets were generated by the
epoch-100 behavior policy in non-reactive simulation.
"""

from __future__ import annotations

import argparse
import json
import pickle
from collections import defaultdict
from pathlib import Path

import numpy as np
import torch

import grpo_selector_v3_cached_common as selector_common
import selector_root_cause_metrics as metrics_common


BASELINE_SHA256 = "1c450bad0cf62ab9110a8101d2ff6c96984541bd975ddea598ddb2add086a514"


def labeled_path(value: str) -> tuple[str, Path]:
    if "=" not in value:
        raise argparse.ArgumentTypeError("expected LABEL=PATH")
    label, path = value.split("=", 1)
    if not label or not path:
        raise argparse.ArgumentTypeError("expected LABEL=PATH")
    return label, Path(path)


def load_policy(label: str, manifest_path: Path, device: torch.device) -> dict:
    manifest_path = manifest_path.expanduser().resolve()
    manifest = json.loads(manifest_path.read_text())
    if manifest.get("status") != "PASS" or manifest.get("schema_version") != 3:
        raise RuntimeError(f"invalid checkpoint manifest: {manifest_path}")
    checkpoint = Path(manifest["checkpoint"]).expanduser().resolve()
    state_path = Path(manifest["scene_selector_state"]).expanduser().resolve()
    if selector_common.sha256_file(checkpoint) != manifest["checkpoint_sha256"]:
        raise RuntimeError(f"materialized checkpoint SHA drifted: {checkpoint}")
    if selector_common.sha256_file(state_path) != manifest["scene_selector_state_sha256"]:
        raise RuntimeError(f"selector state SHA drifted: {state_path}")
    payload = torch.load(state_path, map_location="cpu")
    if payload.get("schema_version") not in (3, 4):
        raise RuntimeError(f"unknown selector payload schema: {state_path}")
    config = dict(payload["scene_selector_config"])
    if config != dict(manifest["selector_payload"]["scene_selector_config"]):
        raise RuntimeError(f"selector config/manifest drifted: {state_path}")
    model = selector_common.model_from_config(config)
    model.load_state_dict(payload["scene_selector_state"], strict=True)
    model.to(device).eval().requires_grad_(False)
    return {
        "label": label,
        "model": model,
        "manifest": manifest,
        "manifest_path": manifest_path,
        "manifest_sha256": selector_common.sha256_file(manifest_path),
        "state_path": state_path,
        "state_method": payload.get("method"),
    }


def rollout_records(root: Path) -> list[Path]:
    root = root.expanduser().resolve()
    paths = sorted(
        (root / "WE_output/openscene_format/diffusiondrive_rollout_records").glob(
            "*_reward.pkl"
        )
    )
    if not paths:
        raise RuntimeError(f"no merged rollout records under {root}")
    return paths


def rollout_outcomes(root: Path) -> dict[str, dict[str, float | bool]]:
    path = (
        root.expanduser().resolve()
        / "WE_output/openscene_format/all_scenes_pdm_averages_NR.csv"
    )
    return metrics_common.load_outcomes(path)


def validate_record(path: Path, row: dict) -> None:
    if row.get("schema_version") != 2 or row.get("record_type") != (
        "diffusiondrive_closed_loop_candidate_reward"
    ):
        raise RuntimeError(f"record schema drifted: {path}")
    if row.get("checkpoint_sha256") != BASELINE_SHA256:
        raise RuntimeError(f"R0 source is not immutable epoch100: {path}")
    arrays = {
        "candidate_features": (20, 256),
        "candidate_trajectories_8": (20, 8, 3),
        "route_bev_features": (20, 8, 256),
        "status_tokens": (1, 256),
        "ego_queries": (1, 256),
        "agents_queries": (30, 256),
        "reference_logits": (20,),
        "candidate_rewards": (20,),
        "candidate_reward_components": (20, 6),
        "candidate_reward_valid_mask": (20,),
    }
    for key, shape in arrays.items():
        value = np.asarray(row.get(key))
        if value.shape != shape:
            raise RuntimeError(f"{path}: {key} shape {value.shape} != {shape}")
        if key != "candidate_reward_valid_mask" and not np.isfinite(value).all():
            raise RuntimeError(f"{path}: {key} is non-finite")
    if not np.asarray(row["candidate_reward_valid_mask"], dtype=np.bool_).all():
        raise RuntimeError(f"invalid candidate reward in {path}")
    if tuple(row.get("reward_component_names", ())) != metrics_common.COMPONENT_NAMES:
        raise RuntimeError(f"reward component order drifted: {path}")
    reference = np.asarray(row["reference_logits"], dtype=np.float64)
    selected = int(row["selected_index"])
    if selected != int(reference.argmax()):
        raise RuntimeError(f"epoch100 behavior action drifted: {path}")


def tensor_batch(rows: list[dict], key: str, device: torch.device) -> torch.Tensor:
    return torch.as_tensor(
        np.stack([np.asarray(row[key]) for row in rows]),
        dtype=torch.float32,
        device=device,
    )


def policy_logits(policy: dict, rows: list[dict], device: torch.device) -> np.ndarray:
    reference = tensor_batch(rows, "reference_logits", device)
    inputs = {
        "candidate_features": tensor_batch(rows, "candidate_features", device),
        "candidate_trajectories": tensor_batch(
            rows, "candidate_trajectories_8", device
        ),
        "route_bev_features": tensor_batch(rows, "route_bev_features", device),
        "status_token": tensor_batch(rows, "status_tokens", device),
        "ego_query": tensor_batch(rows, "ego_queries", device),
        "agents_query": tensor_batch(rows, "agents_queries", device),
    }
    model = policy["model"]
    if getattr(model, "requires_reference_logits", False):
        inputs["reference_logits"] = reference
    with torch.no_grad():
        logits = reference + model(**inputs)
    return logits.float().cpu().numpy()


def append_chunks(target: dict[str, list[np.ndarray]], values: dict[str, np.ndarray]):
    for key, value in values.items():
        target[key].append(np.asarray(value))


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--rollout-root", type=Path, action="append", required=True)
    parser.add_argument("--policy", type=labeled_path, action="append", required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--device", default="cuda")
    parser.add_argument("--batch-size", type=int, default=128)
    parser.add_argument("--temperature", type=float, default=1.0)
    parser.add_argument("--bootstrap-repetitions", type=int, default=10000)
    parser.add_argument("--bootstrap-seed", type=int, default=20260902)
    args = parser.parse_args()
    if args.batch_size <= 0 or args.temperature <= 0:
        raise ValueError("batch size and temperature must be positive")
    device = torch.device(args.device)
    if device.type == "cuda" and not torch.cuda.is_available():
        raise RuntimeError("CUDA requested but unavailable")
    labels = [label for label, _ in args.policy]
    if len(set(labels)) != len(labels):
        raise RuntimeError("duplicate policy label")
    policies = [load_policy(label, path, device) for label, path in args.policy]

    paths = []
    outcomes = {}
    source_roots = []
    for root_argument in args.rollout_root:
        root = root_argument.expanduser().resolve()
        source_roots.append(str(root))
        paths.extend(rollout_records(root))
        for scene, outcome in rollout_outcomes(root).items():
            if scene in outcomes and outcomes[scene] != outcome:
                raise RuntimeError(f"conflicting outcomes for scene {scene}")
            outcomes[scene] = outcome
    if len(set(paths)) != len(paths):
        raise RuntimeError("duplicate rollout record paths")

    chunks = {policy["label"]: defaultdict(list) for policy in policies}
    scenes: list[str] = []
    seen_frames = set()
    for start in range(0, len(paths), args.batch_size):
        batch_paths = paths[start : start + args.batch_size]
        rows = []
        for path in batch_paths:
            with path.open("rb") as stream:
                row = pickle.load(stream)
            validate_record(path, row)
            identity = (str(row["rollout_scene_id"]), int(row["worldengine_step"]))
            if identity in seen_frames:
                raise RuntimeError(f"duplicate logical R0 frame: {identity}")
            seen_frames.add(identity)
            rows.append(row)
            scenes.append(identity[0])
        rewards = np.stack([row["candidate_rewards"] for row in rows])
        components = np.stack([row["candidate_reward_components"] for row in rows])
        reference = np.stack([row["reference_logits"] for row in rows])
        behavior = np.asarray([int(row["selected_index"]) for row in rows])
        for policy in policies:
            logits = policy_logits(policy, rows, device)
            values = metrics_common.frame_metric_arrays(
                logits,
                rewards,
                components,
                reference_logits=reference,
                behavior_indices=behavior,
                temperature=args.temperature,
            )
            append_chunks(chunks[policy["label"]], values)
        if (start // args.batch_size + 1) % 25 == 0:
            print(f"R0 replayed {min(start + args.batch_size, len(paths))}/{len(paths)}")

    methods = {}
    for policy in policies:
        label = policy["label"]
        values = metrics_common.concatenate_metric_chunks(chunks[label])
        methods[label] = {
            "checkpoint_manifest": str(policy["manifest_path"]),
            "checkpoint_manifest_sha256": policy["manifest_sha256"],
            "materialized_checkpoint": policy["manifest"]["checkpoint"],
            "materialized_checkpoint_sha256": policy["manifest"]["checkpoint_sha256"],
            "selector_state": str(policy["state_path"]),
            "selector_state_method": policy["state_method"],
            "counterfactual_ranking": metrics_common.summarize_policy(
                values,
                scenes,
                outcomes,
                bootstrap_repetitions=args.bootstrap_repetitions,
                bootstrap_seed=args.bootstrap_seed,
            ),
        }

    output_payload = {
        "schema_version": 1,
        "status": "PASS",
        "method": "diffusiondrive_selector_root_cause_r0_replay_v1",
        "scope": {
            "behavior_policy": "immutable_epoch100_diffusiondrive",
            "simulation_mode": "NR",
            "interpretation": "counterfactual_ranking_on_epoch100_visited_candidate_sets",
            "on_policy_claim_allowed": False,
            "occupancy_shift_claim_allowed": False,
            "reward_or_components_used_as_selector_inputs": False,
        },
        "source_checkpoint_sha256": BASELINE_SHA256,
        "source_rollout_roots": source_roots,
        "num_records": len(paths),
        "num_scenarios": len(set(scenes)),
        "num_logs": len({metrics_common.log_id(scene) for scene in scenes}),
        "temperature": args.temperature,
        "bootstrap_repetitions": args.bootstrap_repetitions,
        "bootstrap_seed": args.bootstrap_seed,
        "policies": methods,
    }
    output = args.output.expanduser().resolve()
    if output.exists():
        raise RuntimeError(f"refusing to overwrite immutable R0 result: {output}")
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(output_payload, indent=2, sort_keys=True) + "\n")
    print(json.dumps({"status": "PASS", "output": str(output)}, sort_keys=True))


if __name__ == "__main__":
    main()

